proxy:
  host: "0.0.0.0"
  port: "8080"
  admin_port: "9090"  # Admin server for /health and /status

backend:
  - name: "backend-1"
    url: "http://localhost:8081"
    health: "/health"  # Health check endpoint path
    weight: 3  # For weighted load balancing (higher = more traffic)
    enabled: true

  - name: "backend-2"
    url: "http://localhost:8082"
    health: "/health"
    weight: 2
    enabled: true

  - name: "backend-3"
    url: "http://localhost:8083"
    health: "/api/health"  # Custom health endpoint
    weight: 1
    enabled: true

  - name: "backend-4"
    url: "http://localhost:8084"
    health: "/health"
    weight: 1
    enabled: false  # Disabled backend (won't receive traffic)

load-balancer:
  method: "round-robin"  # Options: "round-robin", "random", "least-connections", "weighted"

health-check:
  interval: 10  # Check backends every 10 seconds
  timeout: 5    # Health check request timeout in seconds
