proxy:
  host: "0.0.0.0"
  port: "8080"

backend:
  - name: "backend-1"
    url: "http://localhost:8081"
    enabled: true

  - name: "backend-2"
    url: "http://localhost:8082"
    enabled: true

  - name: "backend-3"
    url: "http://localhost:8083"
    enabled: true

  - name: "backend-4"
    url: "http://localhost:8084"
    enabled: true

load-balancer:
  method: "round-robin"
